site_name: 茕山羊维基
nav:
  - 主页: index.md
  - 会议记录: meeting.md
  - 历史要事: lsys.md
  - 群机构:
    - 茕羊纪律委员会: jljcwyh.md
  - 一些名词: name.md

theme:
  name: material
  language : zh
  favicon: https://img.wsmdn.dpdns.org/img/goat.jpg

plugins:
  - search:
      separator: '[\s\-\.]+'  # 更好地切分中文和符号
      lang: ['zh']            # 明确指定中文语言
   # 提前构建索引，加快加载速度

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition



